version: '3'

services:
  agent:
    build:
      context: ../
      dockerfile: docker/agent/Dockerfile
    # volumes:
    #   - ./agent/src:/usr/src/app
    #   - ./shared:/usr/src/app/shared
    container_name: FIM-agent

  server:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    # volumes:
    #   - ./server/src:/usr/src/app
    #   - ./shared:/usr/src/app/shared
    ports:
      - "5000:5000"
    container_name: FIM-server